spring:
  application:
    name: springboot-admin-app 
  boot:
   admin:
    routes:
     endpoints: 
         - env
         - metrics
         - trace
         - dump
         - jolokia
         - info
         - configprops
         - trace
         - logfile
         - refresh
         - flyway
         - liquibase
         - heapdump
         - hystrix.stream
         - turbine.stream
   
server:
 port: 9995
 
 #Configure Admin App to interact with Eureka Server
 eureka:
  instance:
   client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/
 
 
 